#ifndef		__INTERFACE_H__
#define 	__INTERFACE_H__
#include 	"fpga.h"
#include	"fpga_sm4.h"
#include	"fpga_sm2.h"
#include  "mcu_algorithm.h"
#include  "test.h"
#include "cipher.h"
#define MAINKEY_LEN				SM4_KEY_LEN


//#define FPGA_DATA_LEN(l)	((0 == ((l) % FPGA_BLOCK_LEN))?(l):((l) + FPGA_BLOCK_LEN - ((l) % FPGA_BLOCK_LEN)))


typedef void (*TaskFunc)(FPGAHeader *, MCUHeader *, unsigned char *, unsigned char *);
#define TASK_FUNC(funcname)		void funcname(FPGAHeader *fpgaheader, MCUHeader *mcuheader, unsigned char *indata, unsigned char *outdata)

#define SD_TASK_NUM(c)					(0x00FF & (c))


#define SGD_SHA1		0x00000002
#define SGD_SHA256		0x00000004
#define SGD_RSA			0x00010000
#define SGD_SM3			0x00000001
#define SGD_SM2			0x00020100

//算法标识

#define SGD_ALG			0xff00	//掩码
#define SGD_SM4			0x0400
#define SGD_SM1			0x0100
#define SGD_AES128		0x1000
#define SGD_AES192		0x2000
#define SGD_AES256		0x4000

//模式标识
#define SGD_ECB			0x0001


/**算法标识宏定义*/
//SM4算法ECB加密模式
#define SGD_SM4_ECB           0x00000401
//SM4算法CBC加密模式
#define SGD_SM4_CBC           0x00000402
//SM4算法CFB加密模式
#define SGD_SM4_CFB           0x00000404
//SM4算法OFB加密模式
#define SGD_SM4_OFB           0x00000408
//SM4算法MAC加密模式
#define SGD_SM4_MAC           0x00000410
//SM1算法ECB加密模式
#define SGD_SM1_ECB           0x00000101
//SM1算法CBC加密模式
#define SGD_SM1_CBC           0x00000102
//SM1算法CFB加密模式
#define SGD_SM1_CFB           0x00000104
//SM1算法OFB加密模式
#define SGD_SM1_OFB           0x00000108
//SM1算法MAC加密模式
#define SGD_SM1_MAC           0x00000110
//AES算法ECB加密模式
#define SGD_AES128_ECB        0x00001001
//AES算法CBC加密模式
#define SGD_AES128_CBC        0x00001002
//AES算法MAC加密模式
#define SGD_AES128_MAC        0x00001010
//AES算法ECB加密模式
#define SGD_AES192_ECB        0x00002001
//AES算法CBC加密模式
#define SGD_AES192_CBC        0x00002002
//AES算法MAC加密模式
#define SGD_AES192_MAC        0x00002010
//AES算法ECB加密模式
#define SGD_AES256_ECB        0x00004001
//AES算法CBC加密模式
#define SGD_AES256_CBC        0x00004002
//AES算法MAC加密模式
#define SGD_AES256_MAC        0x00004010
//DES算法ECB加密模式
#define SGD_DES_ECB           0x00008001
//DES算法CBC加密模式
#define SGD_DES_CBC           0x00008002
//DES算法MAC加密模式
#define SGD_DES_MAC           0x00008010
//3DES算法ECB加密模式
#define SGD_3DES_ECB          0x00010001
//3DES算法CBC加密模式
#define SGD_3DES_CBC          0x00010002
//3DES算法MAC加密模式
#define SGD_3DES_MAC          0x00010010



#define	STANDARD_VERSION				0x0018

#define ADMIN_INDEX_MAX		3

void Inter_MCU_CMD(unsigned char *myInData);
void Inter_MCU_CMD1(void);
unsigned char mem_cpy_len(unsigned char *buff, unsigned char * src,uint32_t len);
TASK_FUNC(do_SD_TASK_GETDEVINFO);								
TASK_FUNC(do_SD_TASK_GETKEYACCRINGHT);
TASK_FUNC(do_SD_TASK_DELEKEYACCRINGHT);
TASK_FUNC(do_SD_TASK_EXPSIGNPUB_RSA);
TASK_FUNC(do_SD_TASK_EXPENCPUB_RSA);
TASK_FUNC(do_SD_TASK_GENKEYPAIREXPORT_RSA);
TASK_FUNC(do_SD_TASK_GENKEYWIHTIPK_RSA);
TASK_FUNC(do_SD_TASK_GENKEYWITHEPK_RSA);
TASK_FUNC(do_SD_TASK_IMPORTKEYWITHISK_RSA);
TASK_FUNC(do_SD_TASK_EXPSIGNPUB_ECC);
TASK_FUNC(do_SD_TASK_EXPENCPUB_ECC);
TASK_FUNC(do_SD_TASK_GENKEYPAIREXPORT_ECC);
TASK_FUNC(do_SD_TASK_GENKEYWIHTIPK_ECC);
TASK_FUNC(do_SD_TASK_GENKEYWITHEPK_ECC);
TASK_FUNC(do_SD_TASK_IMPORTKEYWITHISK_ECC);
TASK_FUNC(do_SD_TASK_GENAGREEDATAWITHECC);
TASK_FUNC(do_SD_TASK_GENKEYWITHECC);
TASK_FUNC(do_SD_TASK_GENAGREEANDKEYWITHECC);
TASK_FUNC(do_SD_TASK_GENKEYWIHTKEK);
TASK_FUNC(do_SD_TASK_IMPORTKEYWITHKEK);
TASK_FUNC(do_SD_TASK_IMPORTSESSIONKEY);
TASK_FUNC(do_SD_TASK_DESTORYKEY);
TASK_FUNC(do_SD_TASK_EXTPUBKEYOPER_RSA);
TASK_FUNC(do_SD_TASK_EXTPRIKEYOPER_RSA);
TASK_FUNC(do_SD_TASK_INTPUBKEYOPER_RSA);
TASK_FUNC(do_SD_TASK_INTPRIKEYOPER_RSA);

TASK_FUNC(do_SD_TASK_INTSYMENC_AES);
TASK_FUNC(do_SD_TASK_EXTSYMENC_AES);
TASK_FUNC(do_SD_TASK_INTSYMENC_DES);
TASK_FUNC(do_SD_TASK_EXTSYMENC_DES);
TASK_FUNC(do_SD_TASK_INTSYMDEC_AES);
TASK_FUNC(do_SD_TASK_EXTSYMDEC_AES);
TASK_FUNC(do_SD_TASK_INTSYMDEC_DES);
TASK_FUNC(do_SD_TASK_EXTSYMDEC_DES);
TASK_FUNC(do_SD_TASK_CREATEFILE);
TASK_FUNC(do_SD_TASK_READFILE);
TASK_FUNC(do_SD_TASK_WRITEFILE);
TASK_FUNC(do_SD_TASK_DELETEFILE);
TASK_FUNC(do_SD_TASK_CLEARFILE);
TASK_FUNC(do_SD_TASK_ENUMFILE);
TASK_FUNC(do_SD_TASK_ADDUSER);
TASK_FUNC(do_SD_TASK_USERLOGIN);
TASK_FUNC(do_SD_TASK_USERLOGOUT);
//TASK_FUNC(do_SD_TASK_RESETPWD);	//从协议中删除
TASK_FUNC(do_SD_TASK_DELUSER);
TASK_FUNC(do_SD_TASK_RESETOPERATORPWD);
TASK_FUNC(do_SD_TASK_GETLOGINSTATUS);
TASK_FUNC(do_SD_TASK_CHGOCURPWD);
TASK_FUNC(do_SD_TASK_CONFIGFILE);
TASK_FUNC(do_SD_TASK_BACKUPADMININFO);
TASK_FUNC(do_SD_TASK_RECOVERYADMININFO);
TASK_FUNC(do_SD_TASK_BACKUPOPERATOR);
TASK_FUNC(do_SD_TASK_BACKUPKEY);
TASK_FUNC(do_SD_TASK_BACKUPADMINLOGIN);
TASK_FUNC(do_SD_TASK_BACKUPADMINQUIT);
TASK_FUNC(do_SD_TASK_GETDEVICESTATE);
TASK_FUNC(do_SD_TASK_RECOVEROPERATOR);
TASK_FUNC(do_SD_TASK_CHECKSELF);
TASK_FUNC(do_SD_TASK_CYCLECHECKSELF);
TASK_FUNC(do_SD_TASK_GENDEVKEY);
TASK_FUNC(do_SD_TASK_EXPORTDEVPUBKEY);
TASK_FUNC(do_SD_TASK_GENKEYUSERKEYPAIR);
TASK_FUNC(do_SD_TASK_CHGKEYKEYPAIRPWD);
TASK_FUNC(do_SD_TASK_GENKEK);
TASK_FUNC(do_SD_TASK_DELKEK);
TASK_FUNC(do_SD_TASK_RECOVERKEY);
TASK_FUNC(do_SD_TASK_IMPORTKEYPAIR);
TASK_FUNC(do_SD_TASK_DESKEYPAIR);
TASK_FUNC(do_SD_TASK_GETKEYPAIRNUM);
TASK_FUNC(do_SD_TASK_GETKEYPAIRSTAT);
TASK_FUNC(do_SD_TASK_EXPORTKEYPAIR);
TASK_FUNC(do_SD_TASK_GETUSERKEYCHK);
TASK_FUNC(do_SD_TASK_GETKEKCHK);
TASK_FUNC(do_SD_TASK_IMPORTENCKEY);
TASK_FUNC(do_SD_TASK_IMPORTKEK);
TASK_FUNC(do_SD_TASK_DEVKEKENC);
TASK_FUNC(do_SD_TASK_DEVKEKDEC);
TASK_FUNC(do_SD_TASK_DEVKEKSIGN);
TASK_FUNC(do_SD_TASK_DEVKEKVERIFY);
TASK_FUNC(do_SD_TASK_DESTORYDEV);
TASK_FUNC(do_SD_TASK_CLEARUKEY);
TASK_FUNC(do_SD_MANU_UPDATEDEV);
TASK_FUNC(do_SD_MANU_CLEARMCU);
TASK_FUNC(do_SD_MANU_SETDEVINFO);
TASK_FUNC(do_SD_MANU_CLEARUKEY);
																											
TASK_FUNC(do_SD_TASK_HASHSHA1);
TASK_FUNC(do_SD_TASK_HASHSHA256);
TASK_FUNC(do_SD_TASK_EXCHDIGENVELOP_RSA);
TASK_FUNC(do_SD_TASK_EXCHDIGENVELOP_ECC);

TASK_FUNC(do_SD_TASK_EXTPUBKEYENC_ECC);
TASK_FUNC(do_SD_TASK_EXTPRIKEYDEC_ECC);
TASK_FUNC(do_SD_TASK_INTPUBKEYENC_ECC);
TASK_FUNC(do_SD_TASK_INTPRIKEYDEC_ECC);
TASK_FUNC(do_SD_TASK_GOTOFACTORY);

TASK_FUNC(do_SD_TASK_INTPRIKEYSIGN_ECC);			//内部公钥ECC签名运算
TASK_FUNC(do_SD_TASK_INTPUBKEYVERI_ECC);			//内部私钥ECC验签运算
TASK_FUNC(do_SD_TASK_EXTPRIKEYSIGN_ECC);			//外部公钥ECC签名运算
TASK_FUNC(do_SD_TASK_EXTPUBKEYVERI_ECC);			//外部私钥ECC验签运算

TASK_FUNC(do_SD_TASK_SHA384);								  //SHA384
TASK_FUNC(do_SD_TASK_SHA512);							    //SHA512
TASK_FUNC(do_SD_TASK_INTSYMENC_SM1);					//SM1内部秘钥加密
TASK_FUNC(do_SD_TASK_EXTSYMENC_SM1);					//SM1外部秘钥加密
TASK_FUNC(do_SD_TASK_INTSYMDEC_SM1);					//SM1内部秘钥解密
TASK_FUNC(do_SD_TASK_EXTSYMDEC_SM1);					//SM1外部秘钥解密
TASK_FUNC(do_SD_TASK_GETMUCVERSION);					//获取MCU版本
TASK_FUNC(do_SD_TASK_GOTOFACTORY_NOADMIN);		//恢复出厂态无管理员
//MCU 到驱动的主动函数
int32_t mcutodriver_LOGINSTATUS(void);


#endif
